-- démarrer une transaction afin d'être sûr que tout a été executé
BEGIN;
-- Suppression des tables existantes
DROP TABLE IF EXISTS "recipe", "category", "user";

-- crétion des tables 
CREATE TABLE "category" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL DEFAULT "plat"
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "firstname" TEXT NOT NULL,
    "lastname" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT "member"
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
); 


CREATE TABLE "recipe" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "level" TEXT NOT NULL,
    "rating" INTEGER NOT NULL,
    "time" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
     "category_id" INTEGER NOT NULL REFERENCES "category"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

-- seeding
 
INSERT INTO  "category"("name")
VALUES ('plat'); 

INSERT INTO  "user"("firstname", "lastname", "email", "password", "role")
VALUES ('john', 'doe', 'johndoe@gmail.fr', '$2a$09$QKrPLgKbQifzNQcqyWyToOFjNJudr0STNjAiqcLpDFIYmzi76ISg2' 'member');


INSERT INTO "recipe"("title", "description", "level", "rating", "time", "user_id", "category_id")
VALUES("Blanquette de veau", "Préparation
Couper la viande en petits cubes.
Saisir la viande dans un filet d’huile pendant 3 minutes.
Couper les carottes, les oignons et les champignons en cubes.
Ajouter la farine sur la viande et mélanger.
Verser le jus de raisin sur la viande.
Ajouter les légumes dans le faitout
Verser le bouillon de légumes.
Laisser cuire pendant 15 minutes.
Casser un oeuf et garder le jaune d’oeuf.
Mélanger le jaune d’oeuf, la crème fraiche et le jus de citron.
Verser le mélange dans le faitout.
Laisser mijoter pendant 15 minutes.
Servir et déguster !", "débutant", 3, 60, 1, 1 );

COMMIT;